# Colors Would Paint my Living Room
[syntax]: /projects/markdown/syntax
[dingus]: /projects/markdown/dingus
<h3>By: Samantha Nguyen </h3>
<body><p color="purple"> I've always had a plain white room, but I always go to Ikea and ogle at all the displays. I will be telling you about the unconventional colors I would love to paint my living room.</p></body> </br>
<h2>Dark Green</h2>
<img src = 
"https://github.com/samanthangyn/SamYen/assets/145371375/4b671474-7249-4f4c-8a30-01af65778c43" /> 
<p>A few years ago, I wanted to paint my room black because I liked the ambiance, but I have come to like dark green instead. The darker the color, the more regal it seems. Having a dark brown wooden bookshelf would also look good in a dark green room. And imagine adding gold lights and posters.</p> </br>
<h2>Dark blue</h2>
<img src = "https://github.com/samanthangyn/SamYen/assets/145371375/eb26e260-8afa-4280-b7ea-f1999adafa35" />
<p>Much like the dark green, I think the dark blue looks regal. However, the decorations would be much different. Instead of gold, lamps would have to be silver or obsidian. In my opinion, refrain from using white because it will look tacky against the dark blue.</p>

If you want a wider array of colors (my two recommendations aren't enough?), you should visit the Ikea official website: https://www.ikea.com/us/en/?cid=a1:ps%257Ca2:se%257Ca3:US_ActivateConsumerLed_Behavioural_0_AO_0_en_Search_Brand_HFBMUL_0_EM_IKE-IKE-079_IKEA_FY24_Google_Omni-ROAS_Core_Text_Br_Exact%257Ca4:ikea%20website%257Ca5:e%257Ca6:google%257Ca7:cq%257Cid:IKEA%2520Branded%2520GM%257Ccc:915





